config/routes.rb
Rails.application.routes.draw do
  get "exercises/index"
  get "progress/index"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # My routes
  root "entries#index"
  resources :entries
  resources :exercises, only: [:index] 

  get "progress", to: "progress#index", as: :progress
  get "exercise_images/:id", to: "exercises#image", as: :exercise_image

  if Rails.env.test?
    post '/test/cleanup', to: 'test_support#cleanup'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FitnessTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>

    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js", defer: true %>
    <%= javascript_include_tag "chartkick", "data-turbo-track": "reload", defer: true %>


    <link rel="stylesheet" href="https://www.w3schools.com/w3css/5/w3.css">

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous">
  </head>

<body class="d-flex flex-column min-vh-100 bg-light">

  <!-- FULL-WIDTH NAVBAR -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand fw-bold" href="<%= root_path %>">KofiGainz</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <%= link_to "Workouts", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Progress chart", progress_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Exercise library", exercises_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

        <%= yield %>
      </div>
    </main>

    <footer class="mt-auto py-3 bg-white border-top">
      <div class="container d-flex justify-content-between flex-wrap small text-muted">
        <span>© <%= Time.current.year %> @Philip Afrane</span>
        <span>Solirius Reply</span>
      </div>
    </footer>

    <!-- Bootstrap JS bundle -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"></script>
  </body>
</html>